### ISSUE TITLE
not detecting AMD cards

### ISSUE THREAD

**Issue by slanckma** [aLeX1443/SmartMine#1]
Hi,

my setup is 2xRX580 and 4xGTX1070Ti (each have 8GB). When I start smartmine v0.4.8.3 only the Nvidia 1070 cards are used (can see this via monitoring tool like GPU-Z). The Rx580 are not hashing at all. 

Note that all my cards run fine with other mining tools like Claymore, nicehash, ...

I have put stats.reporting to FALSE, but it still doesn't work.

Congrats on all the work so far, but please fix this.

Thanks,
Sven.

**Comment by slanckma** [comment]
For anybody else running into this. Developers confirmed that AMD will be supported in the next version 0.5.

**Comment by aLeX1443** [comment]
That's right, we are working on adding AMD support in v0.5. Sorry for the inconvenience.
