### ISSUE TITLE
Reading log produced an error

### ISSUE THREAD

**Issue by kunjvaan** [aLeX1443/SmartMine#11]
Waiting for stats always gives back  "Reading log produced an error"

I know my pools are set up correctly, What else could it be?

**Comment by aLeX1443** [comment]
Can you check the logs under /Mining/logs? If you see 'stratum authentication failure' then that pool isn't set up correctly.

**Comment by kunjvaan** [comment]
I have checked there, some of them are blank. I think there maybe something wrong with suprnova pools. Its seems like the miner is not communicating with the pool even though its set up properly

**Comment by aLeX1443** [comment]
You can try going into /Mining/bin/ccminer-alexis test SIB.cmd after editing it and using your username and password.

**Comment by kunjvaan** [comment]
[2017-12-12 08:55:52] Stratum connection failed: Failed to connect to mona.suprnova.cc port 2995: Bad access
[2017-12-12 08:55:52] ...retry after 30 seconds

this is the log

**Comment by aLeX1443** [comment]
That means there is a problem with the way the mona pool has been set up. Could you try logging into mona.suprnova.cc with the account name you entered in SmartMine and double check that the worker name and password is correct?

**Comment by f0x90** [comment]
Getting the same error and I don't see any miners running. I'd really like to see this software succeed. What do you need from me to troubleshoot?

**Comment by aLeX1443** [comment]
v0.5 Beta 2 will show the miner.exe log in a GUI tab, this way you will be able to see if the miner has been set up correctly.
