### ISSUE TITLE
Error in getting profitability data

### ISSUE THREAD

**Issue by aLeX1443** [aLeX1443/SmartMine#13]
If you are getting an error to do with profitability data, please update to the latest version (v0.4.8.5), as this has been resolved.

**Comment by CudaCores** [comment]
I just upgraded to the latest version and getting this...

https://gyazo.com/d6b5c0ad489657ef10b23ba1a2866b2a

**Comment by aLeX1443** [comment]
That error means the application can't connect to the data server. Could you try to access whattomine.com from your browser and see if it works there?
