### ISSUE TITLE
V0.5 Beta "ERROR Failed to read Nvidia GPU logs"

### ISSUE THREAD

**Issue by sombrejester** [aLeX1443/SmartMine#18]
"ERROR Failed to read Nvidia GPU logs" and "INFO Failed to read Nvidia GPU logs. (Support for AMD GPUs coming in the full release)"
I've only setup ETH, SIB, and VIVO so far. I've been getting this error repeatedly when I try to mine.
The revenue is also much higher in smartmine than whattomine for some reason ($13 vs $2).

Windows 7 64bit.
GTX 1070
Smartmine V0.5 Beta

Loving the GUI though :)

**Comment by aLeX1443** [comment]
You have to set your hash rates for each algorithm in the Benchmark window (automatic algorithm benchmarking will come in a future Beta release). Please refer to: https://www.smartmine.org/help for help on how to set everything up.

**Comment by sombrejester** [comment]
Thanks for the response.
I've now set up the hash rates and power consumption for ETH, SIB, and VIVO. All other coins are set to FALSE. I'm still getting the same error upon hitting Run.[https://puu.sh/yMV75/c73accc35f.png](https://puu.sh/yMV75/c73accc35f.png)

**Comment by aLeX1443** [comment]
This is an issue we have recently experienced with one of our testing rigs. It has to do with SmartMine not being able to read the nvidia-smi.exe log. On our rig at least, the computer is mining (can be confirmed by looking at the GPU power consumption with MSI Afterburner, or reading the miner logs (which will be displayed in a GUI tab in Beta 2)

**Comment by Josemagi** [comment]
I had the same problem.
I think you have to install C++ libraries.
The Dev don´t talk us about the libraries required to run smartmine.

**Comment by Josemagi** [comment]
I mean install Microsoft VC++  2013 from https://www.microsoft.com/es-es/download/details.aspx?id=40784
Download http://cryptomining-blog.com/tag/ccminer-alexis-1-0/ 
and replace miner with ccminer and rename it to miner in the
\SmartMine-v0.5-beta.1\bin\ccminer-alexis folder

**Comment by wbattel4607** [comment]
I've got the same issue. It's mining, but continuously fails to read Nvidia GPU logs. This is a fresh install on a rig I finished building an hour ago. I've installed VC++ 2017 Redistributable to get SmartMine to run, and now this is the only issue. As long as it is mining, I guess it's a minor problem, but hopefully it can be resolved! So far 0.5 looks fantastic!

**Comment by aLeX1443** [comment]
Some Nvidia GPUs don't support nvidia-smi (GTX 660, GTX 1060 and others). The printing issue has already been fixed and will available in Beta 2.
