### ISSUE TITLE
v0.5 Beta - Coin Statistics do no accurately reflect the values I entered in Benchmark window

### ISSUE THREAD

**Issue by wbattel4607** [aLeX1443/SmartMine#19]
I know auto-benchmarking isn't yet available, but I manually entered my hash rates and power usage from whattomine and even after saving them the revenues shown for each coin are as they were before, and do not reflect anything close to the values I entered. I don't know if this is intentional (by that I mean, you're already aware and plan to fix it with a later version) or not, but I wanted to let you know.

Thanks.

**Comment by wbattel4607** [comment]
It seems that they do update after restarting the program, but it'd still be preferable if they updated when your pressed `Save`

**Comment by aLeX1443** [comment]
Thank you for letting me know, we'll look into this. Just to clarify, after you enter your hash rate values, press 'Save and Close' and then click on 'Benchmark' the old settings are there?

**Comment by wbattel4607** [comment]
No. The benchmark window does properly save. If I save+close and press Benchmark again, the new values do persist. It is only the main window with the Coin Statistics table that isn't updating until restarting the program.

**Comment by aLeX1443** [comment]
I see what you mean, working on a fix now. Thanks for letting me know :)

**Comment by wbattel4607** [comment]
No problem. Looking forward to the next version!
