### ISSUE TITLE
Miner setup problems

### ISSUE THREAD

**Issue by VinnyT1** [aLeX1443/SmartMine#2]
So yea I'm having problems setting smart miner. Here are the errors....

Waiting for stats...
**Reading log produced an error**

Waiting for stats...
miner restarting due to miner.exe not detected...
Access is denied.

**Reading log produced an error**

miner restarting due to miner.exe not detected...
Access is denied.

miner restarting due to low gpu power detected...
Access is denied.

**Reading log produced an error**

**Comment by Oblivion165** [comment]
Same

**Comment by DerkSchooltink** [comment]
Access denied sounds like permission issues. Have you tried running as admin?

**Comment by BoilerTom** [comment]
I'm getting the exact same problem.  The command line interface keeps putting up these errors and my computer appears to be doing no mining even though the program is telling me mining zencash.  If I try to run the batch file as an administrator, I get a "path not found" error and the cmd window closes itself.
If I run normally (not administrator)
![image](https://user-images.githubusercontent.com/34334201/33704817-cdf64d92-dae2-11e7-801a-25ab669f14bd.png)

if I run as administrator:
![image](https://user-images.githubusercontent.com/34334201/33704842-e38eca1c-dae2-11e7-8073-41d634104161.png)

**Comment by BoilerTom** [comment]
Additional info:  This machine is running a single GTX1080.
Config file:
![image](https://user-images.githubusercontent.com/34334201/33704920-2bafed94-dae3-11e7-94e1-3d277e663ff3.png)

All lines below what I've shown were left alone.

**Comment by slanckma** [comment]
Hi, 

did you download the file from https://github.com/aLeX1443/SmartMine/archive/master.zip ?

From where do you start the application. Is it from within the uncompressed folder itself? Or did you maybe make a copy to your Desktop and launch it from there?

**Comment by BoilerTom** [comment]
The master branch (the zip that you linked to) only contains a single only contains a single 2kb readme file.

I downloaded version 4.8.3 from the following link. 
https://github.com/aLeX1443/SmartMine/releases/download/v0.4.8.3/SmartMine-v0.4.8.3.zip

 I extracted the zip to a folder on my C drive.  The Filepath i'm running the batch file from is:
"C:\Mining Stuff\SmartMine-v0.4.8.3\Run SmartMine v0.4.8.3.bat"

**Comment by slanckma** [comment]
I wonder if it's the space "Mining Stuff" that could cause the problem. Can you try to extract to a new folder that has no space like "MiningStuff"?

**Comment by aLeX1443** [comment]
You can check the \Mining\logs folder to see what the miners are doing and whether or not they're configured properly. The next version of SmartMine coming in a few weeks will make the setup process easier through a GUI and will alert the user when the miner isn't configured properly.

**Comment by aLeX1443** [comment]
This could also be because of the antivirus deleting the mining applications. Try adding the SmartMine folder to the exception list.

**Comment by BoilerTom** [comment]
Looks like the space in the folder name was the culprit!  You may want to add that info to the setup file, or refactor the code so that it can handle white space in the top level path above the batch file folder.  Thanks for the help!

**Comment by slanckma** [comment]
Great to hear you got it solved. Happy mining! Alex1443, can this be added as a fix in the code of v0.5?

**Comment by aLeX1443** [comment]
Already on it. Seeing as this is quite a small fix, I'll release v0.4.8.4 in a few days with this fix and a working currency conversion.

**Comment by aLeX1443** [comment]
v0.4.8.4 has been released. It fixes the currency conversion, but not the spaces in the folder names yet. This will come in v0.5. Thanks everyone for your suggestions!
