### ISSUE TITLE
v0.5 Beta - Log snaps to bottom on new lines

### ISSUE THREAD

**Issue by wbattel4607** [aLeX1443/SmartMine#20]
I'm trying to scroll up in the logs but every time it outputs a new line it snaps to the bottom. Can you make it not snap if the user scrolled up?

Pretty minor issue but it'd be nice! :)

Thanks.

**Comment by aLeX1443** [comment]
We'll either add a button or a checkbox at the bottom of the main window that will toggle auto-scrolling. This will either come in Beta 2 or Beta 3.

**Comment by wbattel4607** [comment]
Okay, sounds good. Can you share your projected timeline for Beta 2, Beta 3, and/or full release?

**Comment by aLeX1443** [comment]
Beta 2 should be released later today if we finish our period of stability testing successfully. Beta 3 should follow in the next few days.

**Comment by aLeX1443** [comment]
This has been resolved in Beta 3
