### ISSUE TITLE
v0.5 Beta - Coin stats refresh interval setting not functioning

### ISSUE THREAD

**Issue by wbattel4607** [aLeX1443/SmartMine#22]
I changed the coin stats refresh interval from the default 1 minute to 10 but it still updates every minute after saving the settings. As far as I can tell it is the only setting not working.

**Comment by aLeX1443** [comment]
This is a known issue that has already been resolved in Beta 2 releasing soon. The stats refresh time is refers to time waiting for profitability statistics. GPU logs are checked at a fixed interval of 5 seconds. The issue was produced by some GPUs not being supported by nvidia-smi

**Comment by wbattel4607** [comment]
Okay, sounds good.
