### ISSUE TITLE
Managing Hardware

### ISSUE THREAD

**Issue by justbotrelatedthings** [aLeX1443/SmartMine#23]
One should have the possibility to oversee and manage hardware (such as in NiceHash GUI) as well as be able to control power and % usage of the hardware (throttle).

**Comment by justbotrelatedthings** [comment]
Would also like to mention that there's no GPU info on v0.5.

**Comment by aLeX1443** [comment]
There is no GPU info in the Beta, the full release will include this in a GUI tab, along with being able to select which cards to mine with.

**Comment by aLeX1443** [comment]
Quick update: we're working on bringing this in Beta 3.

**Comment by aLeX1443** [comment]
This was added in Beta 3
