### ISSUE TITLE
Coin stats refresh timing 

### ISSUE THREAD

**Issue by jiggad369** [aLeX1443/SmartMine#27]
Hi,

I just started using Smartmine but I've noticed that no matter what refresh interval I set it to, the miner operates at 1 minute interval. This is causing the miner to start mining a new coin every minute.

**Comment by aLeX1443** [comment]
Are you modifying the 'coin stats refresh interval' or the 'log refresh interval'?

**Comment by jiggad369** [comment]
The coin stats refresh interval.

I've even tried changing it in the config file but no luck.

**Comment by aLeX1443** [comment]
There does seem to be an issue in Beta 2, this will be fixed in an upcoming Beta. Thank you for bringing this to my attention.

**Comment by jiggad369** [comment]
Great, thanks!

**Comment by aLeX1443** [comment]
For the time being, you can increase the 'Miner switch threshold' so that coins don't switch as often.

**Comment by aLeX1443** [comment]
This was fixed in Beta 3
