### ISSUE TITLE
Miner.exe being used by another process

### ISSUE THREAD

**Issue by hamster3698** [aLeX1443/SmartMine#3]
Hi, ive been trying to set this miner up but every time i launch the miner process it says "miner restarting due to miner.exe not detected...
The process cannot access the file because it is being used by another process."

I have tried running as Admin but that only brings up this "The system cannot find the path specified.
Press any key to continue . . ."

I dont know where to go from here.

**Comment by aLeX1443** [comment]
Have you configured everything in the 'config.txt' and pool_setup.txt' files?

**Comment by aLeX1443** [comment]
This could also be because of the antivirus deleting the mining applications. Try adding the SmartMine folder to the exception list.

**Comment by hamster3698** [comment]
I did manage to fix it, i had one of the pool options setup incorrectly. It does sometimes still do it intermittently though, every couple times starting the miner.

**Comment by aLeX1443** [comment]
We haven't experienced this issue in testing, but it should not be a problem in the upcoming v0.5, as we are completely re-building SmartMine from the ground up.

**Comment by BlivAK** [comment]
Having the same issue. miner used by another process.. It worked for about 2 minutes though

**Comment by aLeX1443** [comment]
Do you have any other mining software running in the background? Try running Task Manager and closing any processes named 'miner.exe'.

**Comment by zhangweidai** [comment]
I have this problem too..  I restarted my machine.  no other miner.exe's.   double checked my config and pool files. no virus scanner. only things running are teamviewer and afterburner, and corsair link

**Comment by aLeX1443** [comment]
You can check if you have by going into \Mining\logs and reading the logs for each miner. If you see 'stratum authentication failure' or a similar error, then there is a mistake in the way you have set up the pools. You can test your credentials by going into \Mining\bin\ccminer-alexis and editing the SIB file with your own credentials, and running that file.

**Comment by aLeX1443** [comment]
We've just found a problem with the setup process. Suprnova used to let you create one account for any of the coins, and have that account be valid for every other Suprnova coin. It turns out that they've changed this so you need to create an account for each of the coins. Please see our updated help section for how to do so: https://www.smartmine.org/help

Apologies for the inconvenience.

**Comment by Quentinb** [comment]
It got this quite often as well. Managed to get it running but did not run for long. Get memory errors and a number of error prompts with some debug message (but with VC++ etc. also got a "not enough power" where my rig worked perfectly well with NiceHash ... until recently that is

**Comment by aLeX1443** [comment]
@Quentinb If you are getting CUDA errors, they are to do with ccminer, so unfortunately there's nothing we can do there. If the errors are strictly to do with memory, increasing the pagefile size to about 8GB should resolve them.

**Comment by Quentinb** [comment]
@aLeX1443 thanks for the feedback. I'll check out the page size.
