### ISSUE TITLE
beta 3 running 10% slower on eth that beta 2

### ISSUE THREAD

**Issue by klove007** [aLeX1443/SmartMine#30]
based of the mh/s readout on the main screen, I am getting 8-10% less in beta 3

**Comment by aLeX1443** [comment]
Which algorithm? Which coin? What was your hash rate before and after?

**Comment by klove007** [comment]
I can email you screenshots of my readout, on ETH there was a console screen that popped up and showed me a hash rate each second.

I was getting 105-108 appearing on this screen and 95-98 that showed up on beta 3

**Comment by aLeX1443** [comment]
That's strange, because EWBF and Ethminer logs were disabled in Beta 2. However, it could have been an error that caused them to print. You can send a screenshot here if you like or join the Discord server  https://discord.gg/dP2WygJ and post it there.
