### ISSUE TITLE
Windows 7 cx_Freeze Python error in main script

### ISSUE THREAD

**Issue by Mobelis** [aLeX1443/SmartMine#33]
http://joxi.ru/4AklwYJHMgkDyr

**Comment by jaaschutz** [comment]
I am a nicehash user currently, thinking of moving over, but the same thing happened to me.

**Comment by aLeX1443** [comment]
That's probably due to a permissions error. Try running SmartMine as an administrator. Also, do you have it installed in AppData?

**Comment by jaaschutz** [comment]
I attempted to install and run the program as administrator. Here is the
Installation Path.

[image: Inline image 2]
but I still get
 [image: Inline image 1]

**Comment by jaaschutz** [comment]
I should note, that I am running Windows 10...NOT Windows 7. Don't know if
that makes a difference in this instance.

**Comment by aLeX1443** [comment]
@jaaschutz, @Mobelis Do you have any Nvidia GPUs in your system? AMD support is coming in a future version.

**Comment by jaaschutz** [comment]
I have 110 Nvidia 1080 tis. No AMDs

**Comment by aLeX1443** [comment]
Would you mind joining our Discord server: https://discord.gg/dP2WygJ ? It may be easier to resolve your issue there, as there are both voice and text channels

**Comment by aLeX1443** [comment]
@jaaschutz  Discord seems to be having issues at the moment. Would you mind moving back to here? Also, how many GPUs do you have in the system you were testing?

**Comment by jaaschutz** [comment]
Yeah I was experiencing same. No problem.

110 Nvidia 1080 tis

**Comment by jaaschutz** [comment]
Oh sorry...for the single rig ...7

**Comment by aLeX1443** [comment]
I see, so when you run SmartMine.exe you get the exact same error message that @Mobelis  was getting?

**Comment by jaaschutz** [comment]
@Mobelis to the left, mine to the right...Don't see any differences
[image: Inline image 1][image: Inline image 2]

**Comment by aLeX1443** [comment]
I'm afraid I can't see the images you uploaded but I can see @Mobelis 's image. Have you mined with a different mining application on that PC before?

**Comment by jaaschutz** [comment]
Yes, Nicehash. 

![image](https://user-images.githubusercontent.com/26257395/35164493-19c44838-fd10-11e7-975a-d717f315b9d2.png)

**Comment by aLeX1443** [comment]
OK, I'm going to have a look at what could be causing that and get back to you as soon as I can.

**Comment by jaaschutz** [comment]
Awesome! Thanks @aLeX1443

**Comment by jaaschutz** [comment]
FYI, if helpful, I am happy to give you access to one of the machines through TeamViewer if you need to check logs or something. @aLeX1443

**Comment by aLeX1443** [comment]
Thanks for the offer, but I doubt any logs were created since the application didn't run for the first time.

**Comment by aLeX1443** [comment]
Could I get you to run a command in a CMD window?

**Comment by jaaschutz** [comment]
Sure

**Comment by aLeX1443** [comment]
Thanks, the command is just to check if nvidia-smi detects the GPUs and is able to read data about them:

cd C:\Program Files\NVIDIA Corporation\NVSMI
nvidia-smi

**Comment by jaaschutz** [comment]
![image](https://user-images.githubusercontent.com/26257395/35164945-0afa6484-fd12-11e7-984c-96453dcaad98.png)
![image](https://user-images.githubusercontent.com/26257395/35164952-15d5cda8-fd12-11e7-82ac-6778a4893c5b.png)

**Comment by aLeX1443** [comment]
Thanks, that looks like it's all in order. I've narrowed the issue down to a certain function. What I can do is upload Beta 3.1 which will still have the issue, but it will give me a more detailed description of the problem. If you're busy I could log in through TeamViewer and test with that, or you could do it yourself, whatever you prefer.

**Comment by jaaschutz** [comment]
B-) I'll DM you the teamviewer info

**Comment by aLeX1443** [comment]
Sure thing :)

**Comment by aLeX1443** [comment]
The issue has been fixed in Beta 4. Please see the Releases section.
