### ISSUE TITLE
[0.5 beta 4] miner.exe not detected for any algorithms

### ISSUE THREAD

**Issue by wbattel4607** [aLeX1443/SmartMine#36]
I just updated my version from 0.5 beta 2 to 0.5 beta 4 and am not able to mine anything,

Everything seems to be working on beta 2 but beta 4 is inoperable for all coins/algos.

I'd post logs but the only thing it says is `miner.exe not detected, restarting` over and over again

**Comment by wbattel4607** [comment]
Could be related to #35

**Comment by aLeX1443** [comment]
Did you copy over the config.ini file from Beta 2 into Beta 4, or did you set things up manually again?

**Comment by wbattel4607** [comment]
@aLeX1443 I copied over the sections that seemed to have the same format+syntax, such as hash rate and algorithm config. I did not copy the entire file, since they probably had syntax changes between versions.

Let me go and try with a fresh install and manually-set config

**Comment by aLeX1443** [comment]
Sure thing, I would use Beta 5 now, since it's just released.

**Comment by wbattel4607** [comment]
Just tried Beta 5 and everything's good. I'm just going to assume it was a config issue.
