### ISSUE TITLE
[0.5 beta 4] Miner restarts when users presses Stop

### ISSUE THREAD

**Issue by wbattel4607** [aLeX1443/SmartMine#38]
This is a minor bug that only applies to those miners that still run in a separate shell as of beta 4 (such as equihash).

When the user presses stop, the running miner closes but immediately restarts. If the user presses stop again, the miner will finally terminate.

**Comment by aLeX1443** [comment]
Can you still see miner.exe in Task Manager after you click Stop? I've tried to replicate the issue, but I don't seem to be experiencing it.

**Comment by wbattel4607** [comment]
I'll gather more data and get back to you.

**Comment by aLeX1443** [comment]
That would be great, thanks.

**Comment by wbattel4607** [comment]
Whatever the cause, this no longer is happening in beta 5.
