### ISSUE TITLE
Currency conversion not working

### ISSUE THREAD

**Issue by slanckma** [aLeX1443/SmartMine#4]
For tracking purposes (issue is already known to developers), currency conversion is currently not working. Use USD until fixed.

**Comment by aLeX1443** [comment]
That's right, a fix is already in place for the upcoming v0.5. ETA 3-4 weeks. We're currently finishing up some features and are doing stability testing.

**Comment by aLeX1443** [comment]
v0.4.8.4 has been released and fixes the exchange rate issue.
