### ISSUE TITLE
Add Electroneum?

### ISSUE THREAD

**Issue by slanckma** [aLeX1443/SmartMine#5]
Hi,

will ETN be added? Or can we add it manually? (for the moment I have the XMR-AEON-STACK-2.0 -20171126 running to mine it)

It's been leading the whattomine.com list for several days now. :-)

Thanks,
Sven.

**Comment by mylove90** [comment]
Why making github while you are not open sourcing the app ?!
Another thing...it should be easier to add or remove coins to mine them
either you add all coins found on whattomine or open the chance for us to add miner apps and associate coins to them

Thanks

**Comment by aLeX1443** [comment]
@slanckma We will be adding most of the coins on WhatToMine in the upcoming v0.5. This should be released in 3-4 weeks. Sorry for the inconvenience.

**Comment by aLeX1443** [comment]
@mylove90 In v0.5 you will be able to add more coins by adding a line in the config.ini, but this shouldn't be necessary as we will be adding most of the coins on WhatToMine anyway.

**Comment by mylove90** [comment]
thanks for response and support
i'll be waiting for v0.5 then

best regards
