### ISSUE TITLE
miner restarting due to miner.exe not detected

### ISSUE THREAD

**Issue by FCBTC** [aLeX1443/SmartMine#7]
I just downloaded SmartMine and got all my accounts configured. The only problem is when I try to actually use SmartMine. "miner restarting due to miner.exe not detected" is the only thing that shows up after "waiting for stats...".
![screenshot](https://user-images.githubusercontent.com/34399960/33797152-f2a0a300-dcd0-11e7-8ce7-e7cf042f1e3b.png)

**Comment by aLeX1443** [comment]
We've just found a problem with the setup process. Suprnova used to let you create one account for any of the coins, and have that account be valid for every other Suprnova coin. It turns out that they've changed this so you need to create an account for each of the coins. Please see our updated help section for how to do so: https://www.smartmine.org/help

This seems to be a problem on Suprnova's side. We didn't notice this because our accounts were created a while ago. Apologies for the inconvenience.

**Comment by Sykres** [comment]
Getting the same problem, and yes I created a new account for every. single. pool.  Very tedious and didn't solve anything.

**Comment by Quentinb** [comment]
Got the same error. It does work every now and then though. I guess it might be an account for each and every single coin. A bit of a mission to get it going.

**Comment by aLeX1443** [comment]
@Quentinb It used to be an easier setup process, granted. However, it only needs to be done once.

**Comment by aLeX1443** [comment]
@Sykres You can try going into /Mining/bin/ccminer-alexis test SIB.cmd after editing it and using your username and password. Note that this .cmd file is not run when using SmartMine, it is purely for testing purposes only.

**Comment by Quentinb** [comment]
I've disabled most of the coins an thus far, it is running fine. Just a question @aLeX1443, setting up ViVo?

**Comment by Skynergy** [comment]
Thanks for the service so far. Also very interested in Vivo, if you can add it. Thank you in advance 😁

**Comment by aLeX1443** [comment]
@Sykres No problem, it will be added along with most of the coins on www.whattomine.com in v0.5

**Comment by bp968** [comment]
Your updated help sections seems to be discussing a program that doesn't exist....   Here it says:  
-------------------------------
Once you have created pool accounts and workers, you can head over to where you installed SmartMine and run SmartMine.exe. On the top left you'll find 'Pool Setup'. Click this button and a new window will appear where you can enter the credentials for the pool accounts you created.
------------------------------------
No "smartMine.exe" exists, and no GUI exists.  What your help *needs* to say is what we need to add to the config file or pool_setup file, but it doesn't.  Any plans to update the help to cover the version of software that currently exists?  Trying to modify the pools file to add in the other logins doesn't seem to work and just coughs up errors on reading the pools file.

**Comment by aLeX1443** [comment]
@bp968  That's right. The main website pages says that is intended for v0.5. Only the section about setting up pool accounts is relevant now. Apologies for the confusion. v0.5 should be releasing in a few weeks, where the setup process will be a lot easier. I would recommend waiting for that if you are having issues setting up v0.4.8.5.
