### ISSUE TITLE
Error in if

### ISSUE THREAD

**Issue by francescocmazza** [aLeX1443/SmartMine#8]
Hello,
I'm trying your mining sw. I keep getting the following error: 

"Waiting for stats...Error in if (power.cons/power.lim < power.threshold.for.restart) { :
  missing value where TRUE/FALSE needed
Calls: ccf9c98c -> repeat.all -> gpu.error.analysis
Execution halted
Premere un tasto per continuare . . ."

I can't find the power.cons setting anywhere. How can I get rid of this error?
Thank you

**Comment by eduelias** [comment]
same here

**Comment by aLeX1443** [comment]
We've had a few reports of this error, but we haven't been able to replicate it on our side. Some users have said that it goes away after restarting the PC. If this does not work however, I would recommend waiting for v0.5 coming in 3-4 weeks, as SmartMine's code has been completely re-written. I apologise for the inconvenience.

**Comment by liljetw** [comment]
What worked for me was set stats.reporting = FALSE

**Comment by liljetw** [comment]
happy mining

**Comment by aLeX1443** [comment]
As @liljetw said, setting stats.reporting = FALSE in the config.txt file should fix this error. However, this will stop GPU stats from being displayed.
