### ISSUE TITLE
Waiting for stats...

### ISSUE THREAD

**Issue by Sykres** [aLeX1443/SmartMine#9]
Appears to be mining, but there is no real information about what's happening.  Just indefinitely says "Waiting for stats..."  I've waited almost 20 minutes... At the same time, I'm looking at my Suprnova account and it's not receiving any info about the worker's status - everything is blank.

**Comment by aLeX1443** [comment]
It's possible that the pool authentication is wrong. Can you check the log under \Mining\logs?
If you see 'stratum authentication failure' then the pool isn't set up correctly.
